baseURL = "https://gaikanomer9.com/"
languageCode = "en-us"
title = "Gaika's Blog"
theme = "pickles"

googleAnalytics = "UA-167304842-1"
[params]
  paginate = 10
  custom_css = ["/css/custom.css"]
  github = "Gaikanomer9"