baseURL = "https://gaikanomer9.com"
title = "Nikita Zavyalov"

theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = "gaikanomer9"

[params]
    author = "Nikita Zavyalov"
    description = "DevOps Engineer and IT Wizard"
    keywords = "blog,developer,personal"
    info = "DevOps Engineer and IT Necromancer"
    avatarURL = "images/avatar.jpeg"
    footerContent = ""

    dateFormat = "January 2, 2006"

    hideFooter = false
    hideCredits = true
    hideCopyright = false
    since = 2020

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "dark"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []


[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/Gaikanomer9"
    target = "_blank"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/nikita-zavyalov-tech/"
    target = "_blank"
[[params.social]]
    name = "Medium"
    icon = "fa fa-medium"
    weight = 5
    url = "https://medium.com/@gaikanomer9"
    target = "_blank"
[[params.social]]
    name = "Habr"
    icon = "fa fa-book"
    weight = 5
    url = "https://habr.com/ru/users/nzavyalov/posts/"
    target = "_blank"
[[params.social]]
    name = "Youtube"
    icon = "fa fa-youtube"
    weight = 4
    url = "https://www.youtube.com/channel/UCBUUvCVvpJk01_RpjIHud_g"
    target = "_blank"

[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"
